export const defaultTheme = {
  name: "default",
  background: "#021F3D",
  backdrop: "#021F3D",
  foreground: "#F5F8FF",
  chrome: "#01162C",
  accent: "#00ADEF",
  neutral: "#0C2A4B",
  fontFamily:
    '"Segoe UI", "Segoe UI Variable", "Segoe UI Web", "Segoe UI Symbol", -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif',
  headingFontFamily:
    '"Segoe UI Semibold", "Segoe UI", "Segoe UI Variable", -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif',
  tilePalette: {
    lms: "#00ADEF",
    profile: "#1BA1E2",
    experience: "#8DC63F",
    stack: "#F7931E",
    testimonials: "#FFC40D",
    contact: "#DA1A1A",
    github: "#2B5797",
    linkedin: "#603CBA",
    sandbox: "#00A600",
    instagram: "#E1306C",
    video: "#FF4500",
  },
  tileContrasts: {
    lms: "light",
    profile: "light",
    experience: "dark",
    stack: "dark",
    testimonials: "dark",
    contact: "light",
    github: "light",
    linkedin: "light",
    sandbox: "light",
    instagram: "light",
    video: "light",
  },
  tileLightText: "#F5F8FF",
  tileDarkText: "#0A2F59",
  tileIcons: {
    lms: "case-study",
    profile: "profile",
    experience: "experience",
    stack: "stack",
    testimonials: "testimonials",
    contact: "contact",
    github: "github",
    linkedin: "linkedin",
    sandbox: "sandbox",
    instagram: "instagram",
    video: "video",
  },
};
