import type { MetroTheme } from "@/lib/theme";

export const pastelTheme: MetroTheme = {
  name: "pastel",
  background: "#1F2236",
  backdrop: "#1F2236",
  foreground: "#F2F4FF",
  chrome: "#252941",
  accent: "#F9A8D4",
  neutral: "#2A2F4A",
  fontFamily: '"Nunito Sans", "Quicksand", "Segoe UI", sans-serif',
  headingFontFamily: '"Quicksand", "Nunito Sans", "Segoe UI", sans-serif',
  tilePalette: {
    lms: "#9BD5F4",
    profile: "#C6F7E2",
    experience: "#FFE9A7",
    stack: "#FBCFE8",
    testimonials: "#FDE1C8",
    contact: "#F8C4CE",
    github: "#C3E4FD",
    linkedin: "#D7C8F7",
    sandbox: "#D1FAE5",
    instagram: "#FBCFE8",
    video: "#FFEDD5",
  },
  tileContrasts: {
    lms: "dark",
    profile: "dark",
    experience: "dark",
    stack: "dark",
    testimonials: "dark",
    contact: "dark",
    github: "dark",
    linkedin: "dark",
    sandbox: "dark",
    instagram: "dark",
    video: "dark",
  },
  tileLightText: "#F2F4FF",
  tileDarkText: "#1F2236",
  tileIcons: {
    lms: "case-study-pastel",
    profile: "profile-pastel",
    experience: "experience-pastel",
    stack: "stack-pastel",
    testimonials: "testimonials-pastel",
    contact: "contact-pastel",
    github: "github-pastel",
    linkedin: "linkedin-pastel",
    sandbox: "sandbox-pastel",
    instagram: "instagram-pastel",
    video: "video-pastel",
  },
};
