import type { MetroTheme } from "@/lib/theme";

export const retroTheme: MetroTheme = {
  name: "retro",
  background: "#140C1C",
  backdrop: "#140C1C",
  foreground: "#F8F4E3",
  chrome: "#0B0612",
  accent: "#FF6F59",
  neutral: "#2D1B3D",
  fontFamily: '"VT323", "Press Start 2P", "Courier New", monospace',
  headingFontFamily: '"Press Start 2P", "VT323", "Courier New", monospace',
  tilePalette: {
    lms: "#5EF38C",
    profile: "#64A2F2",
    experience: "#F896D8",
    stack: "#F8F566",
    testimonials: "#FFD23F",
    contact: "#FF6F59",
    github: "#7D7ABC",
    linkedin: "#8EA4D2",
    sandbox: "#C4F1BE",
    instagram: "#F896D8",
    video: "#FF8E3C",
  },
  tileContrasts: {
    lms: "dark",
    profile: "dark",
    experience: "dark",
    stack: "dark",
    testimonials: "dark",
    contact: "dark",
    github: "dark",
    linkedin: "dark",
    sandbox: "dark",
    instagram: "dark",
    video: "dark",
  },
  tileLightText: "#F8F4E3",
  tileDarkText: "#140C1C",
  tileIcons: {
    lms: "case-study-retro",
    profile: "profile-retro",
    experience: "experience-retro",
    stack: "stack-retro",
    testimonials: "testimonials-retro",
    contact: "contact-retro",
    github: "github-retro",
    linkedin: "linkedin-retro",
    sandbox: "sandbox-retro",
    instagram: "instagram-retro",
    video: "video-retro",
  },
};
